export const formTab = [
  {
    value: "Dados conta",
    label: "Dados conta",
    fields: [
      { value: "Nome Completo", disable: false },
      { value: "CPF", disable: false },
      { value: "RG", disable: false },
      { value: "Sexo", disable: false },
      { value: "Nacionalidade", disable: false },
      { value: "Nome Completo do Pai", disable: false },
      { value: "Nome Completo da Mãe", disable: false },
      { value: "Telefone Celular", disable: false },
      { value: "Data de Nascimento", disable: false },
      { value: "Orgão Emissor", disable: false },
      { value: "Profissão", disable: false },
      { value: "Estado Civil", disable: false },
      { value: "Email: clientalien@dashboard.com", disable: false },
      { value: "Cliente desde: 10/06/2023", disable: true },
    ],
  },
  {
    value: "Dados pessoais",
    label: "Dados pessoais",
    fields: [
      { value: "CEP", disable: false, set: 'zipCode' },
      { value: "Cidade", disable: false, set: 'city' },
      { value: "País", disable: false, set: 'country' },
      { value: "Endereço", disable: false, set: 'addresLine1' },
      { value: "Complemento", disable: false, set: 'addresLine2' },
      { value: "Número", disable: false, set: 'number' },
      { value: "Bairro", disable: false, set: 'district' },
      { value: "UF", disable: false, set: 'state' },
      { value: "IP", disable: true, set: 'ip' },
    ],
  },
  {
    value: "Cartão de crédito",
    label: "Cartão de crédito",
    fields: [
      { value: "Número do cartão", disable: false, set: 'cardNumber' },
      { value: "CPF do titular", disable: false, set: 'cpf' },
      { value: "Limite de crédito", disable: false, set: 'creditLimit' },
      { value: "Nome completo titular", disable: false, set: 'fullName' },
      { value: "Data de validade", disable: false, set: 'expiryDate' },
      { value: "Bandeira", disable: false, set: 'cardFlag' },
    ],
  },
  {
    value: "Dados Bancários",
    label: "Dados Bancários",
    fields: [
      { value: "Banco", disable: false, set: 'bank' },
      { value: "Tipo de conta", disable: false, set: 'accountType' },
      { value: "Saldo atual", disable: false, set: 'currentBalance' },
      { value: "Agência", disable: false, set: 'agency' },
      { value: "Titular", disable: false, set: 'AccountHolder' },
      { value: "Código do banco", disable: false, set: 'bankCode' },
    ],
  },
];
