export const tablesDre = [
  {
    heads: [
      "Referência",
      "Jan - 2023",
      "Fev - 2023",
      "Mar - 2023",
      "Abr - 2023",
      "Mai - 2023",
      "Jun - 2023",
      "Jul - 2023",
      "Ago - 2023",
      "Set - 2023",
      "Out - 2023",
      "Nov - 2023",
      "Dez - 2023",
    ],
  },
  {
    rows: [
      {
        name: "Receita",
        Jan: "01-31 | 12%",
        Fev: "01-31 | 12%",
        Mar: "01-31 | 12%",
        Abr: "01-31 | 12%",
        Mai: "01-31 | 12%",
        Jun: "01-31 | 12%",
        Jul: "01-31 | 12%",
        Ago: "01-31 | 12%",
        Set: "01-31 | 12%",
        Out: "01-31 | 12%",
        Nov: "01-31 | 12%",
        Dez: "01-31 | 12%",
      },
      {
        name: "Despesa",
        Jan: "01-31 | 12%",
        Fev: "01-31 | 12%",
        Mar: "01-31 | 12%",
        Abr: "01-31 | 12%",
        Mai: "01-31 | 12%",
        Jun: "01-31 | 12%",
        Jul: "01-31 | 12%",
        Ago: "01-31 | 12%",
        Set: "01-31 | 12%",
        Out: "01-31 | 12%",
        Nov: "01-31 | 12%",
        Dez: "01-31 | 12%",
      },
      {
        name: "Custo",
        Jan: "01-31 | 12%",
        Fev: "01-31 | 12%",
        Mar: "01-31 | 12%",
        Abr: "01-31 | 12%",
        Mai: "01-31 | 12%",
        Jun: "01-31 | 12%",
        Jul: "01-31 | 12%",
        Ago: "01-31 | 12%",
        Set: "01-31 | 12%",
        Out: "01-31 | 12%",
        Nov: "01-31 | 12%",
        Dez: "01-31 | 12%",
      },
      {
        name: "Resultado",
        Jan: "01-31 | 12%",
        Fev: "01-31 | 12%",
        Mar: "01-31 | 12%",
        Abr: "01-31 | 12%",
        Mai: "01-31 | 12%",
        Jun: "01-31 | 12%",
        Jul: "01-31 | 12%",
        Ago: "01-31 | 12%",
        Set: "01-31 | 12%",
        Out: "01-31 | 12%",
        Nov: "01-31 | 12%",
        Dez: "01-31 | 12%",
      },
    ],
  },
];

export const tablesFluxoDeCaixa = [
  {
    heads: [
      "Data",
      "Banco",
      "Transação",
      "Origem",
      "Tag",
      "Categoria",
      "Referência",
      "Centro de custo",
      "Observações",
    ],
  },
  {
    rows: [
      {
        data: "22 Mai 2023",
        banco: "Bradesco",
        transacao: "Débito",
        origem: "Contratos",
        tag: "M&A",
        categoria: "Sell-Side",
        referencia: "Set 23",
        centroDeCusto: "Sforza",
        observações: "But i Must explain to you how all this mistaken idea",
      },
      {
        data: "22 Mai 2023",
        banco: "Bradesco",
        transacao: "Débito",
        origem: "Contratos",
        tag: "M&A",
        categoria: "Sell-Side",
        referencia: "Set 23",
        centroDeCusto: "Sforza",
        observações: "But i Must explain to you how all this mistaken idea",
      },
      {
        data: "22 Mai 2023",
        banco: "Bradesco",
        transacao: "Débito",
        origem: "Contratos",
        tag: "M&A",
        categoria: "Sell-Side",
        referencia: "Set 23",
        centroDeCusto: "Sforza",
        observações: "But i Must explain to you how all this mistaken idea",
      },
      {
        data: "22 Mai 2023",
        banco: "Bradesco",
        transacao: "Débito",
        origem: "Contratos",
        tag: "M&A",
        categoria: "Sell-Side",
        referencia: "Set 23",
        centroDeCusto: "Sforza",
        observações: "But i Must explain to you how all this mistaken idea",
      },
      {
        data: "22 Mai 2023",
        banco: "Bradesco",
        transacao: "Débito",
        origem: "Contratos",
        tag: "M&A",
        categoria: "Sell-Side",
        referencia: "Set 23",
        centroDeCusto: "Sforza",
        observações: "But i Must explain to you how all this mistaken idea",
      },
      {
        data: "22 Mai 2023",
        banco: "Bradesco",
        transacao: "Débito",
        origem: "Contratos",
        tag: "M&A",
        categoria: "Sell-Side",
        referencia: "Set 23",
        centroDeCusto: "Sforza",
        observações: "But i Must explain to you how all this mistaken idea",
      },
      {
        data: "22 Mai 2023",
        banco: "Bradesco",
        transacao: "Débito",
        origem: "Contratos",
        tag: "M&A",
        categoria: "Sell-Side",
        referencia: "Set 23",
        centroDeCusto: "Sforza",
        observações: "But i Must explain to you how all this mistaken idea",
      },
      {
        data: "22 Mai 2023",
        banco: "Bradesco",
        transacao: "Débito",
        origem: "Contratos",
        tag: "M&A",
        categoria: "Sell-Side",
        referencia: "Set 23",
        centroDeCusto: "Sforza",
        observações: "But i Must explain to you how all this mistaken idea",
      },
      {
        data: "22 Mai 2023",
        banco: "Bradesco",
        transacao: "Débito",
        origem: "Contratos",
        tag: "M&A",
        categoria: "Sell-Side",
        referencia: "Set 23",
        centroDeCusto: "Sforza",
        observações: "But i Must explain to you how all this mistaken idea",
      },
      {
        data: "22 Mai 2023",
        banco: "Bradesco",
        transacao: "Débito",
        origem: "Contratos",
        tag: "M&A",
        categoria: "Sell-Side",
        referencia: "Set 23",
        centroDeCusto: "Sforza",
        observações: "But i Must explain to you how all this mistaken idea",
      },
    ],
  },
];

export const tablesGestor = [
  {
    heads: [
      "Data Cadastro",
      "Sexo",
      "Idade",
      "Nacionalidade",
      "Atuação",
      "Data Nascimento",
      "Limite CC",
      "Limite Conta",
      "Cidade UF",
    ],
  },
  {
    rows: [
      {
        dataCadastro: "22 Mai 2023",
        sexo: "Masculino",
        idade: "37",
        nacionalidade: "Brasileiro",
        atuacao: "Mercado Financeiro",
        dataNascimento: "26/11/1985",
        limiteCc: "123.456.789",
        limiteConta: "123.456.789",
        cidadeUf: "São José do Rio Preto SP",
      },
      {
        dataCadastro: "22 Mai 2023",
        sexo: "Masculino",
        idade: "37",
        nacionalidade: "Brasileiro",
        atuacao: "Mercado Financeiro",
        dataNascimento: "26/11/1985",
        limiteCc: "123.456.789",
        limiteConta: "123.456.789",
        cidadeUf: "São José do Rio Preto SP",
      },
      {
        dataCadastro: "22 Mai 2023",
        sexo: "Masculino",
        idade: "37",
        nacionalidade: "Brasileiro",
        atuacao: "Mercado Financeiro",
        dataNascimento: "26/11/1985",
        limiteCc: "123.456.789",
        limiteConta: "123.456.789",
        cidadeUf: "São José do Rio Preto SP",
      },
      {
        dataCadastro: "22 Mai 2023",
        sexo: "Masculino",
        idade: "37",
        nacionalidade: "Brasileiro",
        atuacao: "Mercado Financeiro",
        dataNascimento: "26/11/1985",
        limiteCc: "123.456.789",
        limiteConta: "123.456.789",
        cidadeUf: "São José do Rio Preto SP",
      },
      {
        dataCadastro: "22 Mai 2023",
        sexo: "Masculino",
        idade: "37",
        nacionalidade: "Brasileiro",
        atuacao: "Mercado Financeiro",
        dataNascimento: "26/11/1985",
        limiteCc: "123.456.789",
        limiteConta: "123.456.789",
        cidadeUf: "São José do Rio Preto SP",
      },
      {
        dataCadastro: "22 Mai 2023",
        sexo: "Masculino",
        idade: "37",
        nacionalidade: "Brasileiro",
        atuacao: "Mercado Financeiro",
        dataNascimento: "26/11/1985",
        limiteCc: "123.456.789",
        limiteConta: "123.456.789",
        cidadeUf: "São José do Rio Preto SP",
      },
      {
        dataCadastro: "22 Mai 2023",
        sexo: "Masculino",
        idade: "37",
        nacionalidade: "Brasileiro",
        atuacao: "Mercado Financeiro",
        dataNascimento: "26/11/1985",
        limiteCc: "123.456.789",
        limiteConta: "123.456.789",
        cidadeUf: "São José do Rio Preto SP",
      },
      {
        dataCadastro: "22 Mai 2023",
        sexo: "Masculino",
        idade: "37",
        nacionalidade: "Brasileiro",
        atuacao: "Mercado Financeiro",
        dataNascimento: "26/11/1985",
        limiteCc: "123.456.789",
        limiteConta: "123.456.789",
        cidadeUf: "São José do Rio Preto SP",
      },
      {
        dataCadastro: "22 Mai 2023",
        sexo: "Masculino",
        idade: "37",
        nacionalidade: "Brasileiro",
        atuacao: "Mercado Financeiro",
        dataNascimento: "26/11/1985",
        limiteCc: "123.456.789",
        limiteConta: "123.456.789",
        cidadeUf: "São José do Rio Preto SP",
      },
      {
        dataCadastro: "22 Mai 2023",
        sexo: "Masculino",
        idade: "37",
        nacionalidade: "Brasileiro",
        atuacao: "Mercado Financeiro",
        dataNascimento: "26/11/1985",
        limiteCc: "123.456.789",
        limiteConta: "123.456.789",
        cidadeUf: "São José do Rio Preto SP",
      },
    ],
  },
];